name: patrique_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.4
  shared_preferences: ^2.5.5
  shimmer: ^3.0.0
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon_fundo_branco.png
    - assets/images/icon_fundo_preto.png
    - assets/images/icon_fundo_rosa.png
    - assets/images/marca_fundo_branco.png
    - assets/images/marca_fundo_preto.png
    - assets/images/marca_fundo_rosa.png
    - assets/images/marca_fundo_transparente.png
    - assets/images/icon_fundo_transparente.png
    